### PR TITLE
Interface Updates

### PR DESCRIPTION
**Pull request by afmartin**

### CODE REVIEW

**Comment by afmartin** [comment]
Don't think I could split it up any further.

**Comment by afmartin** [comment]
I think I fixed everything without screwing up. Once you push your graph changes I want to add a bit more error handling like telling user there is no API Key specified.

**Comment by afmartin** [comment]
O shoot I just realized updating API key won't update program.. don't accept pull request.. I need to fix that.

**Comment by afmartin** [comment]
Key can now be updated and new requests will use the new key now.  Ready for pull at your approve William :)

**Comment by MrMagaw** [comment]
In your settings commit, please add settings.json to the .gitignore, and remove Key.java.
Also, don't forget to change your commits to present tense.

**Comment by afmartin** [comment]
Third time is the charm?

**Comment by afmartin** [comment]
Fixed

**Comment by MrMagaw** [comment]
I swear, that's the last issue I see.

**Pull request merged**
